# Generated by Django 5.1.2 on 2026-04-15 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التمثال (انجليزي كما يظهر من الموديل)')),
                ('label_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('era', models.CharField(max_length=100, verbose_name='العصر')),
                ('museum', models.CharField(max_length=200, verbose_name='المتحف الموجود به')),
                ('description', models.TextField(verbose_name='وصف تفصيلي للتمثال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='statues_db/', verbose_name='صورة مرجعية')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_searched', models.ImageField(upload_to='user_searches/', verbose_name='الصورة التي رفعها المستخدم')),
                ('confidence', models.FloatField(verbose_name='نسبة التأكد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البحث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
                ('statue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
