# Generated by Django 5.1.2 on 2026-06-04 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان بالعربي')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالانجليزي')),
                ('desc_ar', models.TextField(verbose_name='الوصف بالعربي')),
                ('desc_en', models.TextField(verbose_name='الوصف بالانجليزي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandmarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landmarks/', verbose_name='الصورة')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.landmark')),
            ],
        ),
    ]
